version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3002:5173"
    volumes:
      - ..:/app:cached
      - /app/node_modules
    command: sleep infinity
    environment:
      - VITE_HOST=0.0.0.0